name: CI-backend

on: 
  workflow_call:
    inputs:
      environment-name: 
        type: string
        required: true
        description: Env name

jobs:
  ci:
    runs-on: ubuntu-latest
    env:
      PYTHON_VERSION: 3.8
      API_DIR: ./
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: ${{ env.PYTHON_VERSION }}
      
      - uses: actions/checkout@v1

      - name: Install Dependencies
        run: |
          pip3 install -r requirements.txt
        working-directory: ${{ env.API_DIR }}

      - name: Lint with flake8
        id: flake8
        run: |
          flake8 app --show-source --statistics
        working-directory: ${{ env.API_DIR }}

      - name: Test with pytest
        run: |
          python3 manage.py test
        working-directory: ${{ env.API_DIR }}

      - name: Install pytest-cov
        if: github.event_name == 'pull_request'
        run: |
          pip install pytest-cov
        working-directory: ${{ env.API_DIR }}

      - name: Build coverage file
        if: github.event_name == 'pull_request'
        run: |
          pytest --junitxml=pytest.xml --cov-report=term-missing:skip-covered --cov-config=.coveragerc --cov=app app/tests/ | tee pytest-coverage.txt
        working-directory: ${{ env.API_DIR }}

      - name: Pytest coverage comment
        if: github.event_name == 'pull_request'
        uses: MishaKav/pytest-coverage-comment@main
        with:
          pytest-coverage-path: ./api/pytest-coverage.txt
          junitxml-path: ${{ env.API_DIR }}/pytest.xml
        
      
