name: CI-backend

on: 
  workflow_call:
    inputs:
      environment-name: 
        type: string
        required: true
        description: Env name

jobs:
  ci:
    runs-on: ubuntu-latest
      PYTHON_VERSION: 3.8.0
      API_DIR: ./
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      
      - name: Detect Changes on Files
        id: changes
        uses: dorny/paths-filter@v2
        with:
          filters: |
            api:
              - 'app/**'

      - name: Setup Python
        if: steps.changes.outputs.api == 'true'
        uses: actions/setup-python@v2
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install Dependencies
        if: steps.changes.outputs.api == 'true'
        run: |
          pip3 install -r requirements.txt
        working-directory: ${{ env.API_DIR }}

      - name: Lint with flake8
        if: steps.changes.outputs.api == 'true'
        id: flake8
        run: |
          source .venv/bin/activate
          flake8 app --show-source --statistics
        working-directory: ./${{ env.API_DIR }}

      - name: Test with pytest
        if: steps.changes.outputs.api == 'true'
        run: |
          source .venv/bin/activate
          python3 manage.py test
        working-directory: ./${{ env.API_DIR }}

      - name: Install pytest-cov
        if: steps.changes.outputs.api == 'true' && github.event_name == 'pull_request'
        run: |
          source .venv/bin/activate
          pip install pytest-cov
        working-directory: ./${{ env.API_DIR }}

      - name: Build coverage file
        if: steps.changes.outputs.api == 'true' && github.event_name == 'pull_request'
        run: |
          source .venv/bin/activate
          pytest --junitxml=pytest.xml --cov-report=term-missing:skip-covered --cov-config=.coveragerc --cov=app app/tests/ | tee pytest-coverage.txt
        working-directory: ./${{ env.API_DIR }}

      - name: Pytest coverage comment
        if: steps.changes.outputs.api == 'true' && github.event_name == 'pull_request'
        uses: MishaKav/pytest-coverage-comment@main
        with:
          pytest-coverage-path: ./api/pytest-coverage.txt
          junitxml-path: ./${{ env.API_DIR }}/pytest.xml
        
      
