name: CI/CD backend stg

on:
  pull_request:
    branches: [ main ]
    paths:
      - "./**"

jobs:
  ci-stg:
    uses: ./.github/workflows/backend-ci.yml
    with:
      environment-name: stg
    secrets: inherit
